/*
 * Use a JOIN to count the number of English language films in each category.
 * Use table category, film_category, film, and language.
 */
SELECT CATEGORY.NAME, COUNT(FILM_CATEGORY.FILM_ID) AS sum
FROM 
CATEGORY
INNER JOIN
FILM_CATEGORY
ON CATEGORY.CATEGORY_ID = FILM_CATEGORY.CATEGORY_ID
WHERE  FILM_CATEGORY.FILM_ID IN
(
SELECT FILM.FILM_ID
 FROM FILM
INNER JOIN
LANGUAGE
ON FILM.LANGUAGE_ID = LANGUAGE.LANGUAGE_ID
WHERE LANGUAGE.NAME = 'English'
)
GROUP BY CATEGORY.NAME
;

