/*
 * Use a JOIN to order the countries by most profitable,
 * where the profit is the total amount that all customers from that country have payed.
 * Use tables payment, rental, customer, address, city, and country.
 * Order by country alphabetically.
 */
SELECT COUNTRY.COUNTRY, SUM(PAYMENT.AMOUNT) AS PROFIT
FROM PAYMENT
INNER JOIN RENTAL
ON PAYMENT.RENTAL_ID = RENTAL.RENTAL_ID
INNER JOIN CUSTOMER
ON RENTAL.CUSTOMER_ID = CUSTOMER.CUSTOMER_ID
INNER JOIN ADDRESS
ON CUSTOMER.ADDRESS_ID = ADDRESS.ADDRESS_ID
INNER JOIN CITY
ON ADDRESS.CITY_ID = CITY.CITY_ID
INNER JOIN COUNTRY
ON CITY.COUNTRY_ID = COUNTRY.COUNTRY_ID
GROUP BY COUNTRY.COUNTRY
ORDER BY COUNTRY.COUNTRY;

